apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2024-12-13T15:36:10Z","labels":{"managed-by":"prometheus-operator","operated-prometheus":"true"},"name":"prometheus-operated","namespace":"monitoring","ownerReferences":[{"apiVersion":"monitoring.coreos.com/v1","kind":"Prometheus","name":"monitoring-kube-prometheus-prometheus","uid":"667173a3-e4e5-4e17-be8f-08d48be5216d"}],"resourceVersion":"33276","uid":"d697189e-0f69-42b8-9607-8ed004958c50"},"spec":{"clusterIP":"None","clusterIPs":["None"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"http-web","port":9090,"protocol":"TCP","targetPort":"http-web"}],"selector":{"app.kubernetes.io/name":"prometheus"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2024-12-13T15:45:48Z"
  labels:
    managed-by: prometheus-operator
    operated-prometheus: "true"
  name: prometheus-operated
  namespace: monitoring
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    name: monitoring-kube-prometheus-prometheus
    uid: 667173a3-e4e5-4e17-be8f-08d48be5216d
  resourceVersion: "36392"
  uid: e10c635f-d5dd-45fc-bba4-af890917fb54
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-web
    port: 9090
    protocol: TCP
    targetPort: http-web
  selector:
    app.kubernetes.io/name: prometheus
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
