apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: taskscheduler-cert
  namespace: default
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: ingress-ssl-certificate
  dnsNames:
    - www.khoaluantotnghiep.click