name: "Terraform"

on:
  push:
    branches: ["main"]

jobs:
  terraform:
    name: "Terraform"
    # env:
    #   # AWS secrets
    #   AWS_ACCESS_KEY_ID: ${{ secrets.SC_AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{secrets.SC_AWS_SECRET_ACCESS_KEY }}
    #   AWS_REGION: ${{ secrets.SC_AWS_REGION }}

    runs-on: ubuntu-latest
    # Checkout the repository to the GitHub Actions runner
    steps:
      - name: "checkout"
        uses: "actions/checkout@v3"
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./
          framework: terraform

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        run: terraform apply -auto-approve
